name: Deploy Vue3 to GitHub Pages

on:
  push:
    branches:
      - main   # main 分支触发

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      # 2. 安装 Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 3. 安装依赖
      - name: Install dependencies
        run: pnpm install

      # 4. 构建项目
      - name: Build project
        run: pnpm run build:github

      # 5. 部署到 gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist